theme: jekyll-swiss
title: Chris Connelly's Portfolio
description: A portfolio of my work
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_repo: portfolio
github_username: teamallnighter

# Optional social link, you can choose from the following options:
# twitter (default), instagram, medium, or dribbble
social_link: twitter
social_username: teamallnighter

# Set theme color here
# Choose from: black (default), blue, gray, magenta, orange, red, white, and yellow.
theme_color: white

# Build settings
markdown: kramdown
